import { prisma } from '../../index.js';
import { NotFoundError, ValidationError } from '../../lib/errors.js';
import type { PaginationParams } from '../../lib/pagination.js';
import type {
  OrderQuery,
  CreateOneTimeOrderInput,
  UpdateOrderInput,
} from './orders.types.js';
import type { Prisma } from '@prisma/client';
import { shouldDeliverOnDate, isOnVacationHold } from '../../lib/frequency.js';
import { isSystemHoliday, isRouteHoliday } from '../holidays/holidays.service.js';
import { applyPendingQuantityChanges } from '../subscriptions/subscriptions.service.js';

const orderInclude = {
  customer: { select: { id: true, name: true, phone: true, status: true } },
  productVariant: {
    select: {
      id: true,
      unitType: true,
      quantityPerUnit: true,
      sku: true,
      product: { select: { id: true, name: true } },
    },
  },
  route: { select: { id: true, name: true } },
  subscription: { select: { id: true, frequencyType: true } },
} satisfies Prisma.DeliveryOrderInclude;

// ---------------------------------------------------------------------------
// Generate orders for a date
// ---------------------------------------------------------------------------
export interface GenerateOrdersSummary {
  totalCreated: number;
  byRoute: Record<string, number>;
  byProductVariant: Record<string, number>;
}

export async function generateOrdersForDate(targetDate: Date): Promise<GenerateOrdersSummary> {
  // Check system-wide holiday first
  const systemHoliday = await isSystemHoliday(targetDate);
  if (systemHoliday) {
    return { totalCreated: 0, byRoute: {}, byProductVariant: {} };
  }

  // Apply pending quantity changes
  await applyPendingQuantityChanges(targetDate);

  // Get all active subscriptions with related data
  const subscriptions = await prisma.subscription.findMany({
    where: { status: 'active' },
    include: {
      customer: { select: { id: true, status: true, routeId: true } },
      vacationHolds: true,
      productVariant: { select: { id: true, product: { select: { name: true } } } },
    },
  });

  const summary: GenerateOrdersSummary = {
    totalCreated: 0,
    byRoute: {},
    byProductVariant: {},
  };

  for (const sub of subscriptions) {
    // Skip paused/stopped customers
    if (sub.customer.status !== 'active') continue;

    // Check frequency match
    const frequencyInput = {
      frequencyType: sub.frequencyType as 'daily' | 'alternate_day' | 'custom_weekday',
      startDate: sub.startDate,
      weekdays: sub.weekdays,
    };
    if (!shouldDeliverOnDate(frequencyInput, targetDate)) continue;

    // Check vacation holds
    const holdInputs = sub.vacationHolds.map((h) => ({
      startDate: h.startDate,
      endDate: h.endDate,
      resumedAt: h.resumedAt,
    }));
    if (isOnVacationHold(holdInputs, targetDate)) continue;

    // Check route-specific holiday
    const routeId = sub.customer.routeId;
    if (routeId) {
      const routeHol = await isRouteHoliday(routeId, targetDate);
      if (routeHol) continue;
    }

    // Check subscription end date
    if (sub.endDate && targetDate > sub.endDate) continue;

    // Create delivery order — skip duplicates via unique constraint
    try {
      await prisma.deliveryOrder.create({
        data: {
          customerId: sub.customerId,
          productVariantId: sub.productVariantId,
          subscriptionId: sub.id,
          routeId: routeId ?? null,
          deliveryDate: targetDate,
          quantity: sub.quantity,
          status: 'pending',
          isAutoGenerated: true,
        },
      });

      summary.totalCreated++;

      const routeKey = routeId ?? 'unassigned';
      summary.byRoute[routeKey] = (summary.byRoute[routeKey] ?? 0) + 1;

      const variantKey = sub.productVariantId;
      summary.byProductVariant[variantKey] = (summary.byProductVariant[variantKey] ?? 0) + 1;
    } catch (err: any) {
      // Skip duplicates — Prisma unique constraint violation code
      if (err?.code === 'P2002') continue;
      throw err;
    }
  }

  return summary;
}

// ---------------------------------------------------------------------------
// List orders
// ---------------------------------------------------------------------------
export async function listOrders(query: OrderQuery, pagination: PaginationParams) {
  const where: Prisma.DeliveryOrderWhereInput = {};

  if (query.date) where.deliveryDate = new Date(query.date);
  if (query.routeId) where.routeId = query.routeId;
  if (query.customerId) where.customerId = query.customerId;
  if (query.status) where.status = query.status;

  const [orders, total] = await Promise.all([
    prisma.deliveryOrder.findMany({
      where,
      skip: pagination.skip,
      take: pagination.take,
      orderBy: { deliveryDate: 'desc' },
      include: orderInclude,
    }),
    prisma.deliveryOrder.count({ where }),
  ]);

  return { orders, total };
}

// ---------------------------------------------------------------------------
// Get single order
// ---------------------------------------------------------------------------
export async function getOrder(id: string) {
  const order = await prisma.deliveryOrder.findUnique({
    where: { id },
    include: orderInclude,
  });

  if (!order) throw new NotFoundError('Order not found');
  return order;
}

// ---------------------------------------------------------------------------
// Create one-time order
// ---------------------------------------------------------------------------
export async function createOneTimeOrder(input: CreateOneTimeOrderInput, userId: string) {
  // Validate customer exists
  const customer = await prisma.customer.findUnique({ where: { id: input.customerId } });
  if (!customer) throw new NotFoundError('Customer not found');

  // Validate product variant exists and is active
  const variant = await prisma.productVariant.findUnique({ where: { id: input.productVariantId } });
  if (!variant) throw new NotFoundError('Product variant not found');
  if (!variant.isActive) {
    throw new ValidationError('Cannot create order for an inactive product variant');
  }

  // Validate route if provided
  if (input.routeId) {
    const route = await prisma.route.findUnique({ where: { id: input.routeId } });
    if (!route) throw new NotFoundError('Route not found');
  }

  return prisma.deliveryOrder.create({
    data: {
      customerId: input.customerId,
      productVariantId: input.productVariantId,
      subscriptionId: null,
      routeId: input.routeId ?? customer.routeId ?? null,
      deliveryDate: new Date(input.deliveryDate),
      quantity: input.quantity,
      status: 'pending',
      isAutoGenerated: false,
    },
    include: orderInclude,
  });
}

// ---------------------------------------------------------------------------
// Update order (only pending orders)
// ---------------------------------------------------------------------------
export async function updateOrder(id: string, input: UpdateOrderInput) {
  const existing = await prisma.deliveryOrder.findUnique({ where: { id } });
  if (!existing) throw new NotFoundError('Order not found');
  if (existing.status !== 'pending') {
    throw new ValidationError('Can only modify pending orders');
  }

  return prisma.deliveryOrder.update({
    where: { id },
    data: {
      ...(input.quantity !== undefined ? { quantity: input.quantity } : {}),
      ...(input.deliveryNotes !== undefined ? { deliveryNotes: input.deliveryNotes } : {}),
    },
    include: orderInclude,
  });
}

// ---------------------------------------------------------------------------
// Delete order (only pending orders)
// ---------------------------------------------------------------------------
export async function deleteOrder(id: string) {
  const existing = await prisma.deliveryOrder.findUnique({ where: { id } });
  if (!existing) throw new NotFoundError('Order not found');
  if (existing.status !== 'pending') {
    throw new ValidationError('Can only remove pending orders');
  }

  return prisma.deliveryOrder.delete({ where: { id } });
}

// ---------------------------------------------------------------------------
// Order summary for a date
// ---------------------------------------------------------------------------
export async function getOrderSummary(date: Date) {
  const orders = await prisma.deliveryOrder.findMany({
    where: { deliveryDate: date },
    include: {
      route: { select: { id: true, name: true } },
      productVariant: {
        select: {
          id: true,
          unitType: true,
          quantityPerUnit: true,
          sku: true,
          product: { select: { id: true, name: true } },
        },
      },
    },
  });

  const byRoute: Record<string, { routeName: string; count: number; totalQuantity: number }> = {};
  const byProductVariant: Record<string, { variantName: string; count: number; totalQuantity: number }> = {};

  for (const order of orders) {
    // Group by route
    const routeKey = order.routeId ?? 'unassigned';
    const routeName = order.route?.name ?? 'Unassigned';
    if (!byRoute[routeKey]) {
      byRoute[routeKey] = { routeName, count: 0, totalQuantity: 0 };
    }
    byRoute[routeKey].count++;
    byRoute[routeKey].totalQuantity += Number(order.quantity);

    // Group by product variant
    const variantKey = order.productVariantId;
    const variantName = `${order.productVariant.product.name} (${order.productVariant.quantityPerUnit} ${order.productVariant.unitType})`;
    if (!byProductVariant[variantKey]) {
      byProductVariant[variantKey] = { variantName, count: 0, totalQuantity: 0 };
    }
    byProductVariant[variantKey].count++;
    byProductVariant[variantKey].totalQuantity += Number(order.quantity);
  }

  return {
    date: date.toISOString().slice(0, 10),
    totalOrders: orders.length,
    byRoute,
    byProductVariant,
  };
}
