import { prisma } from '../../index.js';
import { NotFoundError, ValidationError } from '../../lib/errors.js';
import { assertPackBreakdownMatchesQuantity } from '../../lib/packaging.js';
import type { PaginationParams } from '../../lib/pagination.js';
import type {
  OrderQuery,
  CreateOneTimeOrderInput,
  UpdateOrderInput,
} from './orders.types.js';
import { Prisma } from '@prisma/client';
import { shouldDeliverOnDate, isOnVacationHold } from '../../lib/frequency.js';
import { isSystemHoliday, isRouteHoliday } from '../holidays/holidays.service.js';
import { applyPendingQuantityChanges } from '../subscriptions/subscriptions.service.js';
import { getMilkCollectionTotalsByDate } from '../milk-collections/milk-collections.service.js';

function getDeliveredQuantity(order: { quantity: Prisma.Decimal; actualQuantity?: Prisma.Decimal | null }) {
  return Number(order.actualQuantity ?? order.quantity);
}

const orderInclude = {
  customer: { select: { id: true, name: true, phone: true, status: true } },
  productVariant: {
    select: {
      id: true,
      unitType: true,
      quantityPerUnit: true,
      sku: true,
      product: { select: { id: true, name: true } },
    },
  },
  route: { select: { id: true, name: true } },
  subscription: { select: { id: true, frequencyType: true } },
  packs: {
    select: {
      id: true,
      packSize: true,
      packCount: true,
    },
    orderBy: { packSize: 'desc' },
  },
} satisfies Prisma.DeliveryOrderInclude;

// ---------------------------------------------------------------------------
// Generate orders for a date
// ---------------------------------------------------------------------------
export interface GenerateOrdersSummary {
  totalCreated: number;
  byRoute: Record<string, number>;
  byProductVariant: Record<string, number>;
}

export async function generateOrdersForDate(targetDate: Date): Promise<GenerateOrdersSummary> {
  // Check system-wide holiday first
  const systemHoliday = await isSystemHoliday(targetDate);
  if (systemHoliday) {
    return { totalCreated: 0, byRoute: {}, byProductVariant: {} };
  }

  // Apply pending quantity changes
  await applyPendingQuantityChanges(targetDate);

  // Get all active subscriptions with related data
  const subscriptions = await prisma.subscription.findMany({
    where: { status: 'active' },
    include: {
      customer: { select: { id: true, status: true, routeId: true } },
      vacationHolds: true,
      productVariant: { select: { id: true, product: { select: { name: true } } } },
      packs: { select: { packSize: true, packCount: true } },
      route: { select: { id: true, name: true, isActive: true } },
    },
  });

  const summary: GenerateOrdersSummary = {
    totalCreated: 0,
    byRoute: {},
    byProductVariant: {},
  };

  for (const sub of subscriptions) {
    // Skip paused/stopped customers
    if (sub.customer.status !== 'active') continue;

    // Check frequency match
    const frequencyInput = {
      frequencyType: sub.frequencyType as 'daily' | 'alternate_day' | 'custom_weekday',
      startDate: sub.startDate,
      weekdays: sub.weekdays,
    };
    if (!shouldDeliverOnDate(frequencyInput, targetDate)) continue;

    // Check vacation holds
    const holdInputs = sub.vacationHolds.map((h) => ({
      startDate: h.startDate,
      endDate: h.endDate,
      resumedAt: h.resumedAt,
    }));
    if (isOnVacationHold(holdInputs, targetDate)) continue;

    // Check route-specific holiday
    const routeId = sub.routeId ?? sub.customer.routeId;
    if (routeId) {
      const routeHol = await isRouteHoliday(routeId, targetDate);
      if (routeHol) continue;
    }

    // Check subscription end date
    if (sub.endDate && targetDate > sub.endDate) continue;

    // Create delivery order — skip duplicates via unique constraint
    try {
      await prisma.deliveryOrder.create({
        data: {
          customerId: sub.customerId,
          productVariantId: sub.productVariantId,
          subscriptionId: sub.id,
          routeId: routeId ?? null,
          deliveryDate: targetDate,
          quantity: sub.quantity,
          deliverySession: sub.deliverySession,
          status: 'pending',
          isAutoGenerated: true,
          packs: sub.packs.length
            ? {
                create: sub.packs.map((pack) => ({
                  packSize: pack.packSize,
                  packCount: pack.packCount,
                })),
              }
            : undefined,
        },
      });

      summary.totalCreated++;

      const routeKey = routeId ?? 'unassigned';
      summary.byRoute[routeKey] = (summary.byRoute[routeKey] ?? 0) + 1;

      const variantKey = sub.productVariantId;
      summary.byProductVariant[variantKey] = (summary.byProductVariant[variantKey] ?? 0) + 1;
    } catch (err: any) {
      // Skip duplicates — Prisma unique constraint violation code
      if (err?.code === 'P2002') continue;
      throw err;
    }
  }

  return summary;
}

// ---------------------------------------------------------------------------
// List orders
// ---------------------------------------------------------------------------
export async function listOrders(query: OrderQuery, pagination: PaginationParams) {
  const where: Prisma.DeliveryOrderWhereInput = {};

  if (query.date) where.deliveryDate = new Date(query.date);
  if (query.routeId) where.routeId = query.routeId;
  if (query.customerId) where.customerId = query.customerId;
  if (query.status) where.status = query.status;

  const [orders, total] = await Promise.all([
    prisma.deliveryOrder.findMany({
      where,
      skip: pagination.skip,
      take: pagination.take,
      orderBy: { deliveryDate: 'desc' },
      include: orderInclude,
    }),
    prisma.deliveryOrder.count({ where }),
  ]);

  return { orders, total };
}

// ---------------------------------------------------------------------------
// Get single order
// ---------------------------------------------------------------------------
export async function getOrder(id: string) {
  const order = await prisma.deliveryOrder.findUnique({
    where: { id },
    include: orderInclude,
  });

  if (!order) throw new NotFoundError('Order not found');
  return order;
}

// ---------------------------------------------------------------------------
// Create one-time order
// ---------------------------------------------------------------------------
export async function createOneTimeOrder(input: CreateOneTimeOrderInput, userId: string) {
  // Validate customer exists
  const customer = await prisma.customer.findUnique({ where: { id: input.customerId } });
  if (!customer) throw new NotFoundError('Customer not found');

  // Validate product variant exists and is active
  const variant = await prisma.productVariant.findUnique({ where: { id: input.productVariantId } });
  if (!variant) throw new NotFoundError('Product variant not found');
  if (!variant.isActive) {
    throw new ValidationError('Cannot create order for an inactive product variant');
  }

  // Validate route if provided
  if (input.routeId) {
    const route = await prisma.route.findUnique({ where: { id: input.routeId } });
    if (!route) throw new NotFoundError('Route not found');
  }

  const packs = assertPackBreakdownMatchesQuantity(input.quantity, input.packBreakdown);

  return prisma.deliveryOrder.create({
    data: {
      customerId: input.customerId,
      productVariantId: input.productVariantId,
      subscriptionId: null,
      routeId: input.routeId ?? customer.routeId ?? null,
      deliveryDate: new Date(input.deliveryDate),
      quantity: input.quantity,
      deliverySession: input.deliverySession,
      status: 'pending',
      isAutoGenerated: false,
      packs: packs.length
        ? {
            create: packs.map((pack) => ({
              packSize: pack.packSize,
              packCount: pack.packCount,
            })),
          }
        : undefined,
    },
    include: orderInclude,
  });
}

// ---------------------------------------------------------------------------
// Update order (only pending orders)
// ---------------------------------------------------------------------------
export async function updateOrder(id: string, input: UpdateOrderInput) {
  const existing = await prisma.deliveryOrder.findUnique({ where: { id } });
  if (!existing) throw new NotFoundError('Order not found');
  if (existing.status !== 'pending') {
    throw new ValidationError('Can only modify pending orders');
  }

  return prisma.$transaction(async (tx) => {
    const nextQuantity = input.quantity !== undefined ? input.quantity : Number(existing.quantity);
    const packs = input.packBreakdown !== undefined
      ? assertPackBreakdownMatchesQuantity(nextQuantity, input.packBreakdown)
      : undefined;

    await tx.deliveryOrder.update({
      where: { id },
      data: {
        ...(input.quantity !== undefined ? { quantity: input.quantity } : {}),
        ...(input.deliverySession !== undefined ? { deliverySession: input.deliverySession } : {}),
        ...(input.deliveryNotes !== undefined ? { deliveryNotes: input.deliveryNotes } : {}),
      },
    });

    if (packs !== undefined) {
      await tx.deliveryOrderPack.deleteMany({ where: { deliveryOrderId: id } });
      if (packs.length) {
        await tx.deliveryOrderPack.createMany({
          data: packs.map((pack) => ({
            deliveryOrderId: id,
            packSize: pack.packSize,
            packCount: pack.packCount,
          })),
        });
      }
    }

    return tx.deliveryOrder.findUniqueOrThrow({
      where: { id },
      include: orderInclude,
    });
  });
}

// ---------------------------------------------------------------------------
// Delete order (only pending orders)
// ---------------------------------------------------------------------------
export async function deleteOrder(id: string) {
  const existing = await prisma.deliveryOrder.findUnique({ where: { id } });
  if (!existing) throw new NotFoundError('Order not found');
  if (existing.status !== 'pending') {
    throw new ValidationError('Can only remove pending orders');
  }

  return prisma.deliveryOrder.delete({ where: { id } });
}

// ---------------------------------------------------------------------------
// Order summary for a date
// ---------------------------------------------------------------------------
export async function getOrderSummary(date: Date) {
  const orders = await prisma.deliveryOrder.findMany({
    where: { deliveryDate: date },
    include: {
      route: { select: { id: true, name: true } },
      productVariant: {
        select: {
          id: true,
          unitType: true,
          quantityPerUnit: true,
          sku: true,
          product: { select: { id: true, name: true } },
        },
      },
    },
  });

  const byRoute: Record<string, { routeName: string; count: number; totalQuantity: number }> = {};
  const byProductVariant: Record<string, { variantName: string; count: number; totalQuantity: number }> = {};

  for (const order of orders) {
    // Group by route
    const routeKey = order.routeId ?? 'unassigned';
    const routeName = order.route?.name ?? 'Unassigned';
    if (!byRoute[routeKey]) {
      byRoute[routeKey] = { routeName, count: 0, totalQuantity: 0 };
    }
    byRoute[routeKey].count++;
    byRoute[routeKey].totalQuantity += Number(order.quantity);

    // Group by product variant
    const variantKey = order.productVariantId;
    const variantName = `${order.productVariant.product.name} (${order.productVariant.quantityPerUnit} ${order.productVariant.unitType})`;
    if (!byProductVariant[variantKey]) {
      byProductVariant[variantKey] = { variantName, count: 0, totalQuantity: 0 };
    }
    byProductVariant[variantKey].count++;
    byProductVariant[variantKey].totalQuantity += Number(order.quantity);
  }

  return {
    date: date.toISOString().slice(0, 10),
    totalOrders: orders.length,
    byRoute,
    byProductVariant,
  };
}

// ---------------------------------------------------------------------------
// Milk summary for a date
// ---------------------------------------------------------------------------
export async function getMilkSummary(date: Date) {
  const [orders, collectionTotals] = await Promise.all([
    prisma.deliveryOrder.findMany({
      where: { deliveryDate: date },
      include: {
        customer: { select: { id: true, name: true, phone: true } },
        route: { select: { id: true, name: true } },
        productVariant: {
          select: {
            id: true,
            unitType: true,
            quantityPerUnit: true,
            product: { select: { name: true } },
          },
        },
      },
    }),
    getMilkCollectionTotalsByDate(date),
  ]);

  const totals = {
    planned: 0,
    delivered: 0,
    pending: 0,
    skipped: 0,
    failed: 0,
    returned: 0,
    over: 0,
    under: 0,
  };

  const byProductSession = new Map<
    string,
    {
      productName: string;
      deliverySession: 'morning' | 'evening';
      routeName: string;
      planned: number;
      delivered: number;
      pending: number;
      skipped: number;
      failed: number;
      returned: number;
      over: number;
      under: number;
    }
  >();

  for (const order of orders) {
    const quantity = Number(order.quantity);
    totals.planned += quantity;

    if (order.status === 'delivered') totals.delivered += getDeliveredQuantity(order as { quantity: Prisma.Decimal; actualQuantity?: Prisma.Decimal | null });
    if (order.status === 'pending') totals.pending += quantity;
    if (order.status === 'skipped') totals.skipped += quantity;
    if (order.status === 'failed') totals.failed += quantity;
    if (order.status === 'returned') totals.returned += quantity;
    if ((order as { adjustmentType?: string }).adjustmentType === 'over') totals.over += Number((order as { adjustmentQuantity?: Prisma.Decimal | null }).adjustmentQuantity ?? 0);
    if ((order as { adjustmentType?: string }).adjustmentType === 'under') totals.under += Number((order as { adjustmentQuantity?: Prisma.Decimal | null }).adjustmentQuantity ?? 0);

    const key = [
      order.productVariant.product.name,
      order.deliverySession,
      order.route?.name ?? 'Unassigned',
    ].join('|');

    if (!byProductSession.has(key)) {
      byProductSession.set(key, {
        productName: order.productVariant.product.name,
        deliverySession: order.deliverySession,
        routeName: order.route?.name ?? 'Unassigned',
        planned: 0,
        delivered: 0,
        pending: 0,
        skipped: 0,
        failed: 0,
        returned: 0,
        over: 0,
        under: 0,
      });
    }

    const row = byProductSession.get(key)!;
    row.planned += quantity;
    if (order.status === 'delivered') row.delivered += getDeliveredQuantity(order as { quantity: Prisma.Decimal; actualQuantity?: Prisma.Decimal | null });
    if (order.status === 'pending') row.pending += quantity;
    if (order.status === 'skipped') row.skipped += quantity;
    if (order.status === 'failed') row.failed += quantity;
    if (order.status === 'returned') row.returned += quantity;
    if ((order as { adjustmentType?: string }).adjustmentType === 'over') row.over += Number((order as { adjustmentQuantity?: Prisma.Decimal | null }).adjustmentQuantity ?? 0);
    if ((order as { adjustmentType?: string }).adjustmentType === 'under') row.under += Number((order as { adjustmentQuantity?: Prisma.Decimal | null }).adjustmentQuantity ?? 0);
  }

  const rows = [...byProductSession.values()]
    .map((row) => ({
      ...row,
      discrepancy: Number((row.planned - row.delivered).toFixed(3)),
    }))
    .sort((a, b) =>
      a.deliverySession.localeCompare(b.deliverySession) ||
      a.routeName.localeCompare(b.routeName) ||
      a.productName.localeCompare(b.productName),
    );

  const customerRows = orders
    .map((order) => ({
      id: order.id,
      customerName: order.customer.name,
      customerPhone: order.customer.phone,
      productName: order.productVariant.product.name,
      routeName: order.route?.name ?? 'Unassigned',
      deliverySession: order.deliverySession,
      quantity: Number(order.quantity),
      actualQuantity: order.status === 'delivered' ? getDeliveredQuantity(order as { quantity: Prisma.Decimal; actualQuantity?: Prisma.Decimal | null }) : null,
      status: order.status,
      adjustmentType: (order as { adjustmentType?: 'exact' | 'over' | 'under' | null }).adjustmentType,
      adjustmentQuantity: Number((order as { adjustmentQuantity?: Prisma.Decimal | null }).adjustmentQuantity ?? 0),
      returnedQuantity: Number(order.returnedQuantity ?? 0),
    }))
    .sort((a, b) =>
      a.deliverySession.localeCompare(b.deliverySession) ||
      a.routeName.localeCompare(b.routeName) ||
      a.customerName.localeCompare(b.customerName) ||
      a.productName.localeCompare(b.productName),
    );

  const bySession = {
    morning: {
      planned: 0,
      delivered: 0,
      pending: 0,
      skipped: 0,
      failed: 0,
      returned: 0,
      over: 0,
      under: 0,
      discrepancy: 0,
      received: collectionTotals.morning,
      receivedVsDelivered: 0,
    },
    evening: {
      planned: 0,
      delivered: 0,
      pending: 0,
      skipped: 0,
      failed: 0,
      returned: 0,
      over: 0,
      under: 0,
      discrepancy: 0,
      received: collectionTotals.evening,
      receivedVsDelivered: 0,
    },
  };

  for (const row of rows) {
    const target = bySession[row.deliverySession];
    target.planned += row.planned;
    target.delivered += row.delivered;
    target.pending += row.pending;
    target.skipped += row.skipped;
    target.failed += row.failed;
    target.returned += row.returned;
    target.over += row.over;
    target.under += row.under;
    target.discrepancy += row.discrepancy;
  }

  for (const session of ['morning', 'evening'] as const) {
    bySession[session].planned = Number(bySession[session].planned.toFixed(3));
    bySession[session].delivered = Number(bySession[session].delivered.toFixed(3));
    bySession[session].pending = Number(bySession[session].pending.toFixed(3));
    bySession[session].skipped = Number(bySession[session].skipped.toFixed(3));
    bySession[session].failed = Number(bySession[session].failed.toFixed(3));
    bySession[session].returned = Number(bySession[session].returned.toFixed(3));
    bySession[session].over = Number(bySession[session].over.toFixed(3));
    bySession[session].under = Number(bySession[session].under.toFixed(3));
    bySession[session].discrepancy = Number(bySession[session].discrepancy.toFixed(3));
    bySession[session].receivedVsDelivered = Number(
      (bySession[session].received - bySession[session].delivered).toFixed(3),
    );
  }

  return {
    date: date.toISOString().slice(0, 10),
    totals: {
      ...totals,
      discrepancy: Number((totals.planned - totals.delivered).toFixed(3)),
    },
    collectionTotals,
    bySession,
    rows,
    customerRows,
  };
}
