import { describe, it, expect, vi, beforeEach } from 'vitest';
import fc from 'fast-check';
import { Prisma } from '@prisma/client';

// ---------------------------------------------------------------------------
// Mock Prisma & pricing
// ---------------------------------------------------------------------------
const mockFindMany = vi.fn();
const mockFindFirst = vi.fn();
const mockFindUnique = vi.fn();
const mockCustomerFindUnique = vi.fn();
const mockCreate = vi.fn();
const mockCreateMany = vi.fn();
const mockCount = vi.fn();
const mockTransaction = vi.fn();
const mockUpdate = vi.fn();
const mockAdjustmentFindMany = vi.fn();
const mockAdjustmentCreate = vi.fn();
const mockDiscountFindMany = vi.fn();
const mockDiscountCreate = vi.fn();

vi.mock('../../index.js', () => ({
  prisma: {
    deliveryOrder: {
      findMany: (...args: any[]) => mockFindMany(...args),
    },
    customer: {
      findUnique: (...args: any[]) => mockCustomerFindUnique(...args),
    },
    invoice: {
      findFirst: (...args: any[]) => mockFindFirst(...args),
      findUnique: (...args: any[]) => mockFindUnique(...args),
      findMany: (...args: any[]) => mockFindMany(...args),
      create: (...args: any[]) => mockCreate(...args),
      update: (...args: any[]) => mockUpdate(...args),
      count: (...args: any[]) => mockCount(...args),
    },
    invoiceLineItem: {
      createMany: (...args: any[]) => mockCreateMany(...args),
    },
    invoiceAdjustment: {
      create: (...args: any[]) => mockAdjustmentCreate(...args),
      findMany: (...args: any[]) => mockAdjustmentFindMany(...args),
    },
    invoiceDiscount: {
      create: (...args: any[]) => mockDiscountCreate(...args),
      findMany: (...args: any[]) => mockDiscountFindMany(...args),
    },
    $transaction: (...args: any[]) => mockTransaction(...args),
  },
  redis: {},
}));

const mockGetEffectivePrice = vi.fn();
vi.mock('../../lib/pricing.js', () => ({
  getEffectivePrice: (...args: any[]) => mockGetEffectivePrice(...args),
}));

const mockCreateLedgerEntry = vi.fn().mockResolvedValue({});
vi.mock('../ledger/ledger.service.js', () => ({
  createLedgerEntry: (...args: any[]) => mockCreateLedgerEntry(...args),
}));

import { generateInvoicesForCycle, addAdjustment, addDiscount } from './billing.service.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Create a Date from a day offset relative to 2024-01-01. */
function dateFromOffset(offset: number): Date {
  const d = new Date(Date.UTC(2024, 0, 1));
  d.setUTCDate(d.getUTCDate() + offset);
  return d;
}

/** Format a Date as YYYY-MM-DD string. */
function toDateStr(d: Date): string {
  return d.toISOString().slice(0, 10);
}

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** A delivery order with random quantity and a variant id. */
const deliveryOrderArb = fc.record({
  id: fc.uuid(),
  customerId: fc.constant('customer-1'),
  productVariantId: fc.constantFrom('variant-a', 'variant-b', 'variant-c'),
  subscriptionId: fc.uuid(),
  routeId: fc.uuid(),
  deliveryDate: fc.integer({ min: 0, max: 29 }).map(dateFromOffset),
  quantity: fc.integer({ min: 1, max: 500 }).map((n) => new Prisma.Decimal(n).div(10)),
  status: fc.constant('delivered' as const),
  isAutoGenerated: fc.constant(true),
  createdAt: fc.constant(new Date()),
  updatedAt: fc.constant(new Date()),
  productVariant: fc.constant({ id: 'variant-a', productId: 'product-1' }),
  skipReason: fc.constant(null),
  failureReason: fc.constant(null),
  returnedQuantity: fc.constant(null),
  deliveryNotes: fc.constant(null),
  deliveredBy: fc.constant(null),
  deliveredAt: fc.constant(null),
});

/** A positive price value (cents converted to decimal). */
const priceArb = fc.integer({ min: 1, max: 100000 }).map((n) => new Prisma.Decimal(n).div(100));

// ---------------------------------------------------------------------------
// Property 13: Invoice total charges equal the sum of all line item totals
// Validates: Requirements 9.3
// ---------------------------------------------------------------------------
describe('Property 13: Invoice total charges equal sum of line item totals', () => {
  beforeEach(() => vi.clearAllMocks());

  it('totalCharges always equals the sum of qty * unitPrice for all line items', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(deliveryOrderArb, { minLength: 1, maxLength: 15 }),
        fc.array(priceArb, { minLength: 1, maxLength: 15 }),
        async (orders, prices) => {
          // Assign consistent product ids to orders and map prices
          const priceByProduct = new Map<string, Prisma.Decimal>();
          priceByProduct.set('product-1', prices[0]);

          // Ensure all orders have the same customerId
          const normalizedOrders = orders.map((o) => ({
            ...o,
            customerId: 'customer-1',
            productVariant: { id: o.productVariantId, productId: 'product-1' },
          }));

          // Mock deliveryOrder.findMany to return our generated orders
          mockFindMany.mockResolvedValueOnce(normalizedOrders);

          // Mock customer.findUnique to return a customer with no pricing category
          mockCustomerFindUnique.mockResolvedValueOnce({ id: 'customer-1', pricingCategory: null });

          // Mock invoice.findFirst: first call for existing cycle invoice (null), second for previous invoice (null)
          mockFindFirst.mockResolvedValueOnce(null);
          mockFindFirst.mockResolvedValueOnce(null);

          // Mock getEffectivePrice to return the generated price for each product
          mockGetEffectivePrice.mockImplementation(async (productId: string) => ({
            price: priceByProduct.get(productId) ?? prices[0],
            effectiveDate: new Date(Date.UTC(2024, 0, 1)),
            branch: null,
          }));

          // Capture what gets created in the transaction
          let capturedInvoiceData: any = null;
          let capturedLineItems: any[] = [];

          mockTransaction.mockImplementation(async (fn: Function) => {
            const tx = {
              invoice: {
                create: async (args: any) => {
                  capturedInvoiceData = args.data;
                  return { id: 'inv-1', ...args.data };
                },
              },
              invoiceLineItem: {
                createMany: async (args: any) => {
                  capturedLineItems = args.data;
                  return { count: args.data.length };
                },
              },
            };
            return fn(tx);
          });

          await generateInvoicesForCycle('2024-01-01', '2024-01-31');

          // Verify: totalCharges must equal sum of all line totals
          const expectedTotal = capturedLineItems.reduce(
            (sum, li) => sum.add(li.lineTotal),
            new Prisma.Decimal(0),
          );

          expect(capturedInvoiceData).not.toBeNull();
          expect(capturedInvoiceData.totalCharges.eq(expectedTotal)).toBe(true);

          // Also verify each line total = quantity * unitPrice
          for (const li of capturedLineItems) {
            const expectedLineTotal = li.quantity.mul(li.unitPrice);
            expect(li.lineTotal.eq(expectedLineTotal)).toBe(true);
          }
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 14: Mid-month price changes apply old price before effective date
//              and new price on/after
// Validates: Requirements 9.4
// ---------------------------------------------------------------------------
describe('Property 14: Mid-month price changes apply correct price per delivery date', () => {
  beforeEach(() => vi.clearAllMocks());

  it('applies old price before change date and new price on/after change date', async () => {
    const oldPriceArb = fc.integer({ min: 1, max: 50000 }).map((n) => new Prisma.Decimal(n).div(100));
    const newPriceArb = fc.integer({ min: 1, max: 50000 }).map((n) => new Prisma.Decimal(n).div(100));
    // Price change day: between day 1 and day 28 of the cycle (offset 1-28)
    const changeDayArb = fc.integer({ min: 1, max: 28 });

    await fc.assert(
      fc.asyncProperty(
        oldPriceArb,
        newPriceArb,
        changeDayArb,
        fc.array(fc.integer({ min: 0, max: 29 }), { minLength: 1, maxLength: 20 }),
        fc.integer({ min: 1, max: 500 }).map((n) => new Prisma.Decimal(n).div(10)),
        async (oldPrice, newPrice, changeDay, deliveryDayOffsets, quantity) => {
          // Deduplicate delivery days
          const uniqueDays = [...new Set(deliveryDayOffsets)];
          if (uniqueDays.length === 0) return;

          const changeDateOffset = changeDay;
          const variantId = 'variant-price-test';

          // Build delivery orders
          const orders = uniqueDays.map((dayOffset, i) => ({
            id: `order-${i}`,
            customerId: 'customer-1',
            productVariantId: variantId,
            subscriptionId: `sub-${i}`,
            routeId: 'route-1',
            deliveryDate: dateFromOffset(dayOffset),
            quantity,
            status: 'delivered' as const,
            isAutoGenerated: true,
            createdAt: new Date(),
            updatedAt: new Date(),
            productVariant: { id: variantId, productId: 'product-1' },
            skipReason: null,
            failureReason: null,
            returnedQuantity: null,
            deliveryNotes: null,
            deliveredBy: null,
            deliveredAt: null,
          }));

          mockFindMany.mockResolvedValueOnce(orders);
          mockCustomerFindUnique.mockResolvedValueOnce({ id: 'customer-1', pricingCategory: null });
          mockFindFirst.mockResolvedValueOnce(null);
          mockFindFirst.mockResolvedValueOnce(null);

          // Mock getEffectivePrice: old price before changeDay, new price on/after
          mockGetEffectivePrice.mockImplementation(async (_productId: string, date: Date) => {
            const dayOffset = Math.round(
              (date.getTime() - new Date(Date.UTC(2024, 0, 1)).getTime()) / (86400000),
            );
            const price = dayOffset < changeDateOffset ? oldPrice : newPrice;
            return {
              price,
              effectiveDate: dayOffset < changeDateOffset
                ? new Date(Date.UTC(2024, 0, 1))
                : dateFromOffset(changeDateOffset),
              branch: null,
            };
          });

          let capturedLineItems: any[] = [];

          mockTransaction.mockImplementation(async (fn: Function) => {
            const tx = {
              invoice: {
                create: async (args: any) => ({ id: 'inv-1', ...args.data }),
              },
              invoiceLineItem: {
                createMany: async (args: any) => {
                  capturedLineItems = args.data;
                  return { count: args.data.length };
                },
              },
            };
            return fn(tx);
          });

          await generateInvoicesForCycle('2024-01-01', '2024-01-31');

          // Verify each line item used the correct price
          for (const li of capturedLineItems) {
            const dayOffset = Math.round(
              (li.deliveryDate.getTime() - new Date(Date.UTC(2024, 0, 1)).getTime()) / 86400000,
            );
            const expectedPrice = dayOffset < changeDateOffset ? oldPrice : newPrice;
            expect(li.unitPrice.eq(expectedPrice)).toBe(true);
          }
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 15: Invoice closing balance equals
//   opening_balance + charges - discounts + adjustments - payments
// Validates: Requirements 9.8
// ---------------------------------------------------------------------------
describe('Property 15: Closing balance formula holds', () => {
  it('closingBalance = openingBalance + charges - discounts + adjustments - payments', () => {
    const decimalArb = fc.integer({ min: 0, max: 1000000 }).map((n) => new Prisma.Decimal(n).div(100));

    fc.assert(
      fc.property(
        decimalArb, // openingBalance
        decimalArb, // totalCharges
        decimalArb, // totalDiscounts
        decimalArb, // totalAdjustments
        decimalArb, // totalPayments
        (openingBalance, totalCharges, totalDiscounts, totalAdjustments, totalPayments) => {
          // This is the exact formula from billing.service.ts
          const closingBalance = openingBalance
            .add(totalCharges)
            .sub(totalDiscounts)
            .add(totalAdjustments)
            .sub(totalPayments);

          // Verify the formula identity
          const reconstructed = closingBalance
            .sub(openingBalance)
            .sub(totalCharges)
            .add(totalDiscounts)
            .sub(totalAdjustments)
            .add(totalPayments);

          // reconstructed should be 0 (the formula is self-consistent)
          expect(reconstructed.eq(new Prisma.Decimal(0))).toBe(true);

          // Also verify the forward formula directly
          const expected = openingBalance
            .add(totalCharges)
            .sub(totalDiscounts)
            .add(totalAdjustments)
            .sub(totalPayments);
          expect(closingBalance.eq(expected)).toBe(true);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('closing balance is computed correctly in generateInvoicesForCycle', async () => {
    const decimalArb = fc.integer({ min: 0, max: 500000 }).map((n) => new Prisma.Decimal(n).div(100));

    await fc.assert(
      fc.asyncProperty(
        decimalArb, // opening balance from previous invoice
        fc.array(
          fc.record({
            quantity: fc.integer({ min: 1, max: 100 }).map((n) => new Prisma.Decimal(n).div(10)),
            price: fc.integer({ min: 1, max: 10000 }).map((n) => new Prisma.Decimal(n).div(100)),
          }),
          { minLength: 1, maxLength: 10 },
        ),
        async (openingBalance, items) => {
          // Build delivery orders from items
          const orders = items.map((item, i) => ({
            id: `order-${i}`,
            customerId: 'customer-1',
            productVariantId: 'variant-1',
            subscriptionId: `sub-${i}`,
            routeId: 'route-1',
            deliveryDate: dateFromOffset(i),
            quantity: item.quantity,
            status: 'delivered' as const,
            isAutoGenerated: true,
            createdAt: new Date(),
            updatedAt: new Date(),
            productVariant: { id: 'variant-1', productId: 'product-1' },
            skipReason: null,
            failureReason: null,
            returnedQuantity: null,
            deliveryNotes: null,
            deliveredBy: null,
            deliveredAt: null,
          }));

          mockFindMany.mockResolvedValueOnce(orders);

          // Mock customer.findUnique
          mockCustomerFindUnique.mockResolvedValueOnce({ id: 'customer-1', pricingCategory: null });

          // First findFirst: existing cycle invoice (null), second: previous invoice with opening balance
          mockFindFirst.mockResolvedValueOnce(null);
          mockFindFirst.mockResolvedValueOnce({
            id: 'prev-inv',
            closingBalance: openingBalance,
            billingCycleEnd: new Date(Date.UTC(2023, 11, 31)), // before cycle start
          });

          // Map each order to its price
          let priceIndex = 0;
          mockGetEffectivePrice.mockImplementation(async () => {
            const price = items[priceIndex % items.length].price;
            priceIndex++;
            return { price, effectiveDate: new Date(Date.UTC(2024, 0, 1)), branch: null };
          });

          let capturedInvoiceData: any = null;

          mockTransaction.mockImplementation(async (fn: Function) => {
            const tx = {
              invoice: {
                create: async (args: any) => {
                  capturedInvoiceData = args.data;
                  return { id: 'inv-1', ...args.data };
                },
              },
              invoiceLineItem: {
                createMany: async (args: any) => ({ count: args.data.length }),
              },
            };
            return fn(tx);
          });

          await generateInvoicesForCycle('2024-01-01', '2024-01-31');

          expect(capturedInvoiceData).not.toBeNull();

          // For new invoices, discounts/adjustments/payments are 0
          // So closing = opening + charges
          const expectedCharges = items.reduce(
            (sum, item) => sum.add(item.quantity.mul(item.price)),
            new Prisma.Decimal(0),
          );

          const expectedClosing = openingBalance.add(expectedCharges);

          expect(capturedInvoiceData.openingBalance.eq(openingBalance)).toBe(true);
          expect(capturedInvoiceData.totalCharges.eq(expectedCharges)).toBe(true);
          expect(capturedInvoiceData.totalDiscounts.eq(new Prisma.Decimal(0))).toBe(true);
          expect(capturedInvoiceData.totalAdjustments.eq(new Prisma.Decimal(0))).toBe(true);
          expect(capturedInvoiceData.totalPayments.eq(new Prisma.Decimal(0))).toBe(true);
          expect(capturedInvoiceData.closingBalance.eq(expectedClosing)).toBe(true);
        },
      ),
      { numRuns: 200 },
    );
  });
});


// ---------------------------------------------------------------------------
// Unit tests for addAdjustment (Req 9.5)
// ---------------------------------------------------------------------------
describe('addAdjustment', () => {
  beforeEach(() => vi.clearAllMocks());

  const baseInvoice = {
    id: 'inv-1',
    customerId: 'cust-1',
    isCurrent: true,
    openingBalance: new Prisma.Decimal('100'),
    totalCharges: new Prisma.Decimal('500'),
    totalDiscounts: new Prisma.Decimal('0'),
    totalAdjustments: new Prisma.Decimal('0'),
    totalPayments: new Prisma.Decimal('0'),
    closingBalance: new Prisma.Decimal('600'),
    paymentStatus: 'unpaid',
  };

  function setupTransaction() {
    mockTransaction.mockImplementation(async (fn: Function) => {
      const tx = {
        invoiceAdjustment: {
          create: mockAdjustmentCreate,
          findMany: mockAdjustmentFindMany,
        },
        invoice: {
          update: mockUpdate,
        },
      };
      return fn(tx);
    });
  }

  it('throws NotFoundError for non-existent invoice', async () => {
    mockFindUnique.mockResolvedValueOnce(null);
    await expect(addAdjustment('bad-id', { adjustmentType: 'credit', amount: 10, reason: 'test' }, 'user-1'))
      .rejects.toThrow('Invoice not found');
  });

  it('throws ValidationError for superseded invoice', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice, isCurrent: false });
    await expect(addAdjustment('inv-1', { adjustmentType: 'credit', amount: 10, reason: 'test' }, 'user-1'))
      .rejects.toThrow('Cannot adjust a superseded invoice');
  });

  it('creates a debit adjustment and recalculates totals', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice });
    setupTransaction();

    mockAdjustmentCreate.mockResolvedValueOnce({});
    mockAdjustmentFindMany.mockResolvedValueOnce([
      { adjustmentType: 'debit', amount: new Prisma.Decimal('50') },
    ]);

    const updatedInvoice = { ...baseInvoice, totalAdjustments: new Prisma.Decimal('50') };
    mockUpdate.mockResolvedValueOnce(updatedInvoice);

    const result = await addAdjustment('inv-1', { adjustmentType: 'debit', amount: 50, reason: 'Late fee' }, 'user-1');

    expect(mockAdjustmentCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        invoiceId: 'inv-1',
        adjustmentType: 'debit',
        reason: 'Late fee',
      }),
    });

    // closingBalance = 100 + 500 - 0 + 50 - 0 = 650
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        totalAdjustments: new Prisma.Decimal('50'),
        closingBalance: new Prisma.Decimal('650'),
        paymentStatus: 'unpaid',
      }),
    }));
  });

  it('creates a credit adjustment and recalculates totals', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice });
    setupTransaction();

    mockAdjustmentCreate.mockResolvedValueOnce({});
    mockAdjustmentFindMany.mockResolvedValueOnce([
      { adjustmentType: 'credit', amount: new Prisma.Decimal('200') },
    ]);

    mockUpdate.mockResolvedValueOnce({});

    await addAdjustment('inv-1', { adjustmentType: 'credit', amount: 200, reason: 'Goodwill' }, 'user-1');

    // closingBalance = 100 + 500 - 0 + (-200) - 0 = 400
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        totalAdjustments: new Prisma.Decimal('-200'),
        closingBalance: new Prisma.Decimal('400'),
        paymentStatus: 'unpaid',
      }),
    }));
  });

  it('sets payment_status to paid when closing balance <= 0 after credit', async () => {
    const paidInvoice = {
      ...baseInvoice,
      totalPayments: new Prisma.Decimal('500'),
      closingBalance: new Prisma.Decimal('100'),
    };
    mockFindUnique.mockResolvedValueOnce(paidInvoice);
    setupTransaction();

    mockAdjustmentCreate.mockResolvedValueOnce({});
    mockAdjustmentFindMany.mockResolvedValueOnce([
      { adjustmentType: 'credit', amount: new Prisma.Decimal('100') },
    ]);

    mockUpdate.mockResolvedValueOnce({});

    await addAdjustment('inv-1', { adjustmentType: 'credit', amount: 100, reason: 'Correction' }, 'user-1');

    // closingBalance = 100 + 500 - 0 + (-100) - 500 = 0
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        paymentStatus: 'paid',
      }),
    }));
  });
});

// ---------------------------------------------------------------------------
// Unit tests for addDiscount (Req 9.6)
// ---------------------------------------------------------------------------
describe('addDiscount', () => {
  beforeEach(() => vi.clearAllMocks());

  const baseInvoice = {
    id: 'inv-1',
    customerId: 'cust-1',
    isCurrent: true,
    openingBalance: new Prisma.Decimal('100'),
    totalCharges: new Prisma.Decimal('500'),
    totalDiscounts: new Prisma.Decimal('0'),
    totalAdjustments: new Prisma.Decimal('0'),
    totalPayments: new Prisma.Decimal('0'),
    closingBalance: new Prisma.Decimal('600'),
    paymentStatus: 'unpaid',
  };

  function setupTransaction() {
    mockTransaction.mockImplementation(async (fn: Function) => {
      const tx = {
        invoiceDiscount: {
          create: mockDiscountCreate,
          findMany: mockDiscountFindMany,
        },
        invoice: {
          update: mockUpdate,
        },
      };
      return fn(tx);
    });
  }

  it('throws NotFoundError for non-existent invoice', async () => {
    mockFindUnique.mockResolvedValueOnce(null);
    await expect(addDiscount('bad-id', { discountType: 'fixed', value: 10 }, 'user-1'))
      .rejects.toThrow('Invoice not found');
  });

  it('throws ValidationError for superseded invoice', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice, isCurrent: false });
    await expect(addDiscount('inv-1', { discountType: 'fixed', value: 10 }, 'user-1'))
      .rejects.toThrow('Cannot add discount to a superseded invoice');
  });

  it('creates a fixed discount and recalculates totals', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice });
    setupTransaction();

    mockDiscountCreate.mockResolvedValueOnce({});
    mockDiscountFindMany.mockResolvedValueOnce([
      { amount: new Prisma.Decimal('75') },
    ]);

    mockUpdate.mockResolvedValueOnce({});

    await addDiscount('inv-1', { discountType: 'fixed', value: 75 }, 'user-1');

    // Discount amount for fixed = value = 75
    expect(mockDiscountCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        invoiceId: 'inv-1',
        discountType: 'fixed',
        value: new Prisma.Decimal('75'),
        amount: new Prisma.Decimal('75'),
      }),
    });

    // closingBalance = 100 + 500 - 75 + 0 - 0 = 525
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        totalDiscounts: new Prisma.Decimal('75'),
        closingBalance: new Prisma.Decimal('525'),
        paymentStatus: 'unpaid',
      }),
    }));
  });

  it('creates a percentage discount and calculates amount from totalCharges', async () => {
    mockFindUnique.mockResolvedValueOnce({ ...baseInvoice });
    setupTransaction();

    // 10% of 500 = 50
    mockDiscountCreate.mockResolvedValueOnce({});
    mockDiscountFindMany.mockResolvedValueOnce([
      { amount: new Prisma.Decimal('50') },
    ]);

    mockUpdate.mockResolvedValueOnce({});

    await addDiscount('inv-1', { discountType: 'percentage', value: 10 }, 'user-1');

    // Discount amount for percentage = totalCharges * (value/100) = 500 * 0.10 = 50
    expect(mockDiscountCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        discountType: 'percentage',
        value: new Prisma.Decimal('10'),
        amount: new Prisma.Decimal('50'),
      }),
    });

    // closingBalance = 100 + 500 - 50 + 0 - 0 = 550
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        totalDiscounts: new Prisma.Decimal('50'),
        closingBalance: new Prisma.Decimal('550'),
      }),
    }));
  });

  it('sets payment_status to paid when discount makes closing balance <= 0', async () => {
    const invoiceWithPayments = {
      ...baseInvoice,
      totalPayments: new Prisma.Decimal('550'),
    };
    mockFindUnique.mockResolvedValueOnce(invoiceWithPayments);
    setupTransaction();

    mockDiscountCreate.mockResolvedValueOnce({});
    mockDiscountFindMany.mockResolvedValueOnce([
      { amount: new Prisma.Decimal('50') },
    ]);

    mockUpdate.mockResolvedValueOnce({});

    await addDiscount('inv-1', { discountType: 'fixed', value: 50 }, 'user-1');

    // closingBalance = 100 + 500 - 50 + 0 - 550 = 0
    expect(mockUpdate).toHaveBeenCalledWith(expect.objectContaining({
      data: expect.objectContaining({
        paymentStatus: 'paid',
      }),
    }));
  });
});

// ---------------------------------------------------------------------------
// Feature: product-level-pricing, Property 11: Billing resolves price via product from variant
// Validates: Requirements 7.1
// ---------------------------------------------------------------------------
describe('Property 11: Billing resolves price via product from variant', () => {
  beforeEach(() => vi.clearAllMocks());

  /** Arbitrary: generate a product id and a set of variant ids that belong to it. */
  const productArb = fc.record({
    productId: fc.uuid(),
    variantIds: fc.array(fc.uuid(), { minLength: 1, maxLength: 3 }),
  });

  /** Arbitrary: generate 1-3 products, each with 1-3 variants. */
  const productsArb = fc.array(productArb, { minLength: 1, maxLength: 3 });

  /** Arbitrary: a positive price value. */
  const priceValArb = fc.integer({ min: 1, max: 100000 }).map((n) => new Prisma.Decimal(n).div(100));

  /** Arbitrary: a pricing category (or null for default). */
  const categoryArb = fc.oneof(fc.constant(null), fc.constant('cat-1'), fc.constant('cat-2'));

  it('calls getEffectivePrice with productVariant.productId (not variantId) and line item price matches', async () => {
    await fc.assert(
      fc.asyncProperty(
        productsArb,
        priceValArb,
        categoryArb,
        async (products, basePrice, pricingCategory) => {
          // Build delivery orders: one per variant across all products
          const orders: any[] = [];
          const priceByProduct = new Map<string, Prisma.Decimal>();

          let priceMultiplier = 1;
          for (const prod of products) {
            const productPrice = basePrice.mul(priceMultiplier);
            priceByProduct.set(prod.productId, productPrice);
            priceMultiplier++;

            for (const variantId of prod.variantIds) {
              orders.push({
                id: `order-${variantId}`,
                customerId: 'customer-1',
                productVariantId: variantId,
                subscriptionId: `sub-${variantId}`,
                routeId: 'route-1',
                deliveryDate: new Date(Date.UTC(2024, 0, 15)),
                quantity: new Prisma.Decimal('1'),
                status: 'delivered' as const,
                isAutoGenerated: true,
                createdAt: new Date(),
                updatedAt: new Date(),
                productVariant: { id: variantId, productId: prod.productId },
                skipReason: null,
                failureReason: null,
                returnedQuantity: null,
                deliveryNotes: null,
                deliveredBy: null,
                deliveredAt: null,
              });
            }
          }

          // Mock deliveryOrder.findMany
          mockFindMany.mockResolvedValueOnce(orders);

          // Mock customer with the generated pricing category
          mockCustomerFindUnique.mockResolvedValueOnce({
            id: 'customer-1',
            pricingCategory,
          });

          // No existing invoice
          mockFindFirst.mockResolvedValueOnce(null);
          // No previous invoice
          mockFindFirst.mockResolvedValueOnce(null);

          // Track all calls to getEffectivePrice
          const effectivePriceCalls: { productId: string; date: Date; branch: any; category: any }[] = [];

          mockGetEffectivePrice.mockImplementation(
            async (productId: string, date: Date, branch: any, category: any) => {
              effectivePriceCalls.push({ productId, date, branch, category });
              return {
                price: priceByProduct.get(productId) ?? basePrice,
                effectiveDate: new Date(Date.UTC(2024, 0, 1)),
                branch: null,
              };
            },
          );

          let capturedLineItems: any[] = [];

          mockTransaction.mockImplementation(async (fn: Function) => {
            const tx = {
              invoice: {
                create: async (args: any) => ({ id: 'inv-1', ...args.data }),
              },
              invoiceLineItem: {
                createMany: async (args: any) => {
                  capturedLineItems = args.data;
                  return { count: args.data.length };
                },
              },
            };
            return fn(tx);
          });

          await generateInvoicesForCycle('2024-01-01', '2024-01-31');

          // Verify: getEffectivePrice was called with productId (not variantId)
          // for every order
          expect(effectivePriceCalls.length).toBe(orders.length);

          for (let i = 0; i < orders.length; i++) {
            const order = orders[i];
            const call = effectivePriceCalls[i];

            // CRITICAL: must use productVariant.productId, NOT productVariantId
            expect(call.productId).toBe(order.productVariant.productId);
            expect(call.productId).not.toBe(order.productVariantId);

            // Must pass the customer's pricing category
            expect(call.category).toBe(pricingCategory);
          }

          // Verify: each line item's unitPrice matches the product-level effective price
          for (const li of capturedLineItems) {
            const matchingOrder = orders.find((o: any) => o.id === li.deliveryOrderId);
            expect(matchingOrder).toBeDefined();

            const expectedPrice = priceByProduct.get(matchingOrder.productVariant.productId);
            expect(expectedPrice).toBeDefined();
            expect(li.unitPrice.eq(expectedPrice!)).toBe(true);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
