import { useState, useCallback } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api } from '@/lib/api';
import { useAuth } from '@/hooks/useAuth';
import { useModalFocusTrap } from '@/hooks/useModalFocusTrap';

interface DeliveryOrder {
  id: string;
  customer: { id: string; name: string; phone: string };
  productVariant: { id: string; product: { name: string }; unitType: string; quantityPerUnit: number };
  route?: { id: string; name: string };
  deliveryDate: string;
  quantity: number;
  deliverySession: 'morning' | 'evening';
  packs?: Array<{ packSize: number | string; packCount: number }>;
  status: 'pending' | 'delivered' | 'skipped' | 'failed' | 'returned';
  isAutoGenerated: boolean;
  deliveredBy?: { name: string };
  deliveredAt?: string;
}

interface OrderSummary {
  totalOrders: number;
  byStatus: Record<string, number>;
  byRoute: Array<{ routeId: string; routeName: string; count: number }>;
}

interface Holiday {
  id: string;
  holidayDate: string;
  description?: string;
  isSystemWide: boolean;
}

interface Route {
  id: string;
  name: string;
}

interface CustomerOption {
  id: string;
  name: string;
}

interface SubscriptionOption {
  id: string;
  customer: { id: string; name: string };
  route?: { id: string; name: string } | null;
  productVariant: { id: string; product: { name: string }; unitType: string; quantityPerUnit: number };
  quantity: number;
  deliverySession: 'morning' | 'evening';
  packs?: Array<{ packSize: number | string; packCount: number }>;
  status: 'active' | 'paused' | 'cancelled';
}

interface ListResponse {
  data: DeliveryOrder[];
  pagination: { page: number; limit: number; total: number; totalPages: number };
}

const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-gray-100 text-gray-800',
  delivered: 'bg-green-100 text-green-800',
  skipped: 'bg-yellow-100 text-yellow-800',
  failed: 'bg-red-100 text-red-800',
  returned: 'bg-purple-100 text-purple-800',
};

export default function DailyOperationsPage() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [routeFilter, setRouteFilter] = useState('');
  const [page, setPage] = useState(1);
  const [addOrderModal, setAddOrderModal] = useState(false);
  const [addOverspillModal, setAddOverspillModal] = useState(false);
  const [editOrder, setEditOrder] = useState<DeliveryOrder | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const closeDeleteModal = useCallback(() => setDeleteTarget(null), []);
  const { modalRef: deleteModalRef } = useModalFocusTrap(!!deleteTarget, closeDeleteModal);
  const [generateConfirm, setGenerateConfirm] = useState(false);
  const closeGenerateModal = useCallback(() => setGenerateConfirm(false), []);
  const { modalRef: generateModalRef } = useModalFocusTrap(generateConfirm, closeGenerateModal);
  const limit = 20;

  const params = new URLSearchParams({ date, page: String(page), limit: String(limit) });
  if (routeFilter) params.set('routeId', routeFilter);

  const { data: ordersData, isLoading } = useQuery({
    queryKey: ['orders', date, routeFilter, page],
    queryFn: () => api.get<ListResponse>(`/api/v1/orders?${params}`),
  });

  const { data: summaryData } = useQuery({
    queryKey: ['orders-summary', date],
    queryFn: () => api.get<OrderSummary>(`/api/v1/orders/summary?date=${date}`),
  });

  const { data: holidays } = useQuery({
    queryKey: ['holidays'],
    queryFn: () => api.get<{ data: Holiday[] }>('/api/v1/holidays'),
  });

  const { data: routes } = useQuery({
    queryKey: ['routes-list'],
    queryFn: () => api.get<{ data: Route[] }>('/api/v1/delivery/routes?limit=100'),
  });

  const isHoliday = holidays?.data?.some(
    (h) => h.holidayDate === date && h.isSystemWide
  );
  const holidayInfo = holidays?.data?.find(
    (h) => h.holidayDate === date && h.isSystemWide
  );

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api.delete(`/api/v1/orders/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      setDeleteTarget(null);
    },
  });

  const generateMutation = useMutation({
    mutationFn: () => api.post('/api/v1/orders/generate', { targetDate: date }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      setGenerateConfirm(false);
    },
  });

  return (
    <div>
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4">
        <div className="flex items-center gap-3">
          <h1 className="text-xl font-semibold text-gray-900">Daily Operations</h1>
          <Link to="/orders/summary" className="text-sm text-blue-600 hover:underline">Milk Summary</Link>
        </div>
        <div className="flex gap-2 print:hidden">
          <button
            onClick={() => setAddOverspillModal(true)}
            className="inline-flex items-center rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-medium text-amber-900 hover:bg-amber-100"
            aria-label="Add overspill order"
          >
            + Add Overspill
          </button>
          <button
            onClick={() => setAddOrderModal(true)}
            className="inline-flex items-center rounded-md bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-700"
            aria-label="Add one-time order"
          >
            + Add Order
          </button>
          {user?.role === 'super_admin' && (
            <button
              onClick={() => setGenerateConfirm(true)}
              className="inline-flex items-center rounded-md bg-green-600 px-3 py-2 text-sm font-medium text-white hover:bg-green-700"
              aria-label="Generate daily orders"
            >
              Generate Orders
            </button>
          )}
        </div>
      </div>

      {/* Date and filters */}
      <div className="flex flex-col sm:flex-row gap-2 mb-4 print:hidden">
        <input
          type="date"
          value={date}
          onChange={(e) => { setDate(e.target.value); setPage(1); }}
          className="rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          aria-label="Select delivery date"
        />
        <select
          value={routeFilter}
          onChange={(e) => { setRouteFilter(e.target.value); setPage(1); }}
          className="rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          aria-label="Filter by route"
        >
          <option value="">All routes</option>
          {routes?.data?.map((r) => (
            <option key={r.id} value={r.id}>{r.name}</option>
          ))}
        </select>
      </div>

      {/* Holiday indicator */}
      {isHoliday && (
        <div className="mb-4 rounded-md bg-orange-50 border border-orange-200 px-4 py-3 text-sm text-orange-800" role="alert">
          🎉 Holiday: {holidayInfo?.description || 'System-wide holiday'} — No auto-generated orders for this date.
        </div>
      )}

      {/* Summary cards */}
      {summaryData && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
          <div className="bg-white rounded-lg border border-gray-200 p-3">
            <p className="text-xs text-gray-500">Total Orders</p>
            <p className="text-lg font-semibold">{summaryData.totalOrders}</p>
          </div>
          <div className="bg-white rounded-lg border border-gray-200 p-3">
            <p className="text-xs text-gray-500">Delivered</p>
            <p className="text-lg font-semibold text-green-700">{summaryData.byStatus?.delivered ?? 0}</p>
          </div>
          <div className="bg-white rounded-lg border border-gray-200 p-3">
            <p className="text-xs text-gray-500">Pending</p>
            <p className="text-lg font-semibold text-gray-700">{summaryData.byStatus?.pending ?? 0}</p>
          </div>
          <div className="bg-white rounded-lg border border-gray-200 p-3">
            <p className="text-xs text-gray-500">Skipped/Failed</p>
            <p className="text-lg font-semibold text-red-700">{(summaryData.byStatus?.skipped ?? 0) + (summaryData.byStatus?.failed ?? 0)}</p>
          </div>
        </div>
      )}

      {isLoading && <p className="text-sm text-gray-500" aria-live="polite">Loading…</p>}

      {/* Orders table */}
      <div className="overflow-x-auto bg-white rounded-lg border border-gray-200">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Customer</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Product</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Qty</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Session</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Route</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
              <th scope="col" className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase print:hidden">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {ordersData?.data?.map((o) => (
              <tr key={o.id} className="hover:bg-gray-50">
                <td className="px-4 py-3 text-sm">{o.customer.name}</td>
                <td className="px-4 py-3 text-sm">{o.productVariant?.product?.name} ({o.productVariant?.quantityPerUnit} {o.productVariant?.unitType})</td>
                <td className="px-4 py-3 text-sm">
                  <div>{o.quantity}</div>
                  <div className="text-xs text-gray-500">
                    {o.packs?.length ? o.packs.map((pack) => `${pack.packCount} x ${Number(pack.packSize)}L`).join(', ') : 'No packs'}
                  </div>
                </td>
                <td className="px-4 py-3 text-sm capitalize">{o.deliverySession}</td>
                <td className="px-4 py-3 text-sm">{o.route?.name ?? '—'}</td>
                <td className="px-4 py-3 text-sm">
                  <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_COLORS[o.status] ?? ''}`}>{o.status}</span>
                </td>
                <td className="px-4 py-3 text-sm text-gray-500">{o.isAutoGenerated ? 'Auto' : 'Manual'}</td>
                <td className="px-4 py-3 text-sm text-right space-x-2 print:hidden">
                  {o.status === 'pending' && (
                    <>
                      <button onClick={() => setEditOrder(o)} className="text-blue-600 hover:underline text-xs" aria-label={`Edit order for ${o.customer.name}`}>Edit</button>
                      <button onClick={() => setDeleteTarget(o.id)} className="text-red-600 hover:underline text-xs" aria-label={`Remove order for ${o.customer.name}`}>Remove</button>
                    </>
                  )}
                </td>
              </tr>
            ))}
            {ordersData?.data?.length === 0 && (
              <tr><td colSpan={8} className="px-4 py-8 text-center text-sm text-gray-500">No orders for this date</td></tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {ordersData?.pagination && ordersData.pagination.totalPages > 1 && (
        <div className="flex items-center justify-between mt-4">
          <p className="text-sm text-gray-500">Page {ordersData.pagination.page} of {ordersData.pagination.totalPages} ({ordersData.pagination.total} total)</p>
          <div className="flex gap-2">
            <button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-md border border-gray-300 px-3 py-1 text-sm disabled:opacity-50">Previous</button>
            <button disabled={page >= ordersData.pagination.totalPages} onClick={() => setPage(page + 1)} className="rounded-md border border-gray-300 px-3 py-1 text-sm disabled:opacity-50">Next</button>
          </div>
        </div>
      )}

      {/* Add Order Modal */}
      {addOrderModal && <AddOrderModal date={date} onClose={() => setAddOrderModal(false)} />}

      {/* Add Overspill Modal */}
      {addOverspillModal && <AddOverspillModal date={date} onClose={() => setAddOverspillModal(false)} />}

      {/* Edit Order Modal */}
      {editOrder && <EditOrderModal order={editOrder} onClose={() => setEditOrder(null)} />}

      {/* Delete confirmation */}
      {deleteTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" role="dialog" aria-modal="true" aria-labelledby="delete-order-title">
          <div ref={deleteModalRef} className="bg-white rounded-lg p-6 max-w-sm w-full mx-4 shadow-xl">
            <h2 id="delete-order-title" className="text-lg font-semibold text-gray-900 mb-2">Remove Order</h2>
            <p className="text-sm text-gray-600 mb-4">Are you sure you want to remove this order?</p>
            <div className="flex justify-end gap-2">
              <button onClick={closeDeleteModal} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">Cancel</button>
              <button onClick={() => deleteMutation.mutate(deleteTarget)} disabled={deleteMutation.isPending} className="rounded-md bg-red-600 px-3 py-1.5 text-sm text-white hover:bg-red-700 disabled:opacity-50">
                {deleteMutation.isPending ? 'Removing…' : 'Remove'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Generate confirmation */}
      {generateConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" role="dialog" aria-modal="true" aria-labelledby="generate-title">
          <div ref={generateModalRef} className="bg-white rounded-lg p-6 max-w-sm w-full mx-4 shadow-xl">
            <h2 id="generate-title" className="text-lg font-semibold text-gray-900 mb-2">Generate Daily Orders</h2>
            <p className="text-sm text-gray-600 mb-4">Generate delivery orders for {date}? This will create orders from active subscriptions.</p>
            <div className="flex justify-end gap-2">
              <button onClick={closeGenerateModal} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">Cancel</button>
              <button onClick={() => generateMutation.mutate()} disabled={generateMutation.isPending} className="rounded-md bg-green-600 px-3 py-1.5 text-sm text-white hover:bg-green-700 disabled:opacity-50">
                {generateMutation.isPending ? 'Generating…' : 'Generate'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function AddOverspillModal({ date, onClose }: { date: string; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [customerId, setCustomerId] = useState('');
  const [subscriptionId, setSubscriptionId] = useState('');
  const [quantity, setQuantity] = useState('');
  const [notes, setNotes] = useState('');
  const [packRows, setPackRows] = useState<Array<{ packSize: string; packCount: string }>>([{ packSize: '', packCount: '' }]);
  const { modalRef } = useModalFocusTrap(true, onClose);

  const { data: customers } = useQuery({
    queryKey: ['overspill-customers'],
    queryFn: () => api.get<{ data: CustomerOption[] }>('/api/v1/customers?limit=500&status=active'),
  });

  const { data: subscriptionsData } = useQuery({
    queryKey: ['overspill-subscriptions', customerId],
    queryFn: () => api.get<{ data: SubscriptionOption[] }>(`/api/v1/subscriptions?customerId=${customerId}&status=active&limit=100`),
    enabled: Boolean(customerId),
  });

  const subscriptions = subscriptionsData?.data ?? [];
  const selectedSubscription = subscriptions.find((subscription) => subscription.id === subscriptionId);

  const mutation = useMutation({
    mutationFn: (data: {
      customerId: string;
      productVariantId: string;
      routeId?: string;
      quantity: number;
      deliveryDate: string;
      deliverySession: string;
      deliveryNotes?: string;
      packBreakdown: Array<{ packSize: number; packCount: number }>;
    }) => api.post('/api/v1/orders', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      onClose();
    },
  });

  const packTotal = packRows.reduce((sum, pack) => sum + (Number(pack.packSize) || 0) * (Number(pack.packCount) || 0), 0);
  const quantityValue = Number(quantity);
  const hasPackRows = packRows.some((pack) => pack.packSize || pack.packCount);
  const packMismatch = hasPackRows && !Number.isNaN(quantityValue) && Math.abs(packTotal - quantityValue) > 0.001;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" role="dialog" aria-modal="true" aria-labelledby="add-overspill-title">
      <div ref={modalRef} className="bg-white rounded-lg p-6 max-w-lg w-full mx-4 shadow-xl">
        <h2 id="add-overspill-title" className="text-lg font-semibold text-gray-900 mb-2">Add Overspill</h2>
        <p className="text-sm text-gray-600 mb-4">
          Create an extra same-day delivery on top of an existing active subscription.
        </p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            if (!selectedSubscription) return;
            mutation.mutate({
              customerId,
              productVariantId: selectedSubscription.productVariant.id,
              routeId: selectedSubscription.route?.id ?? undefined,
              quantity: Number(quantity),
              deliveryDate: date,
              deliverySession: selectedSubscription.deliverySession,
              deliveryNotes: notes || `Overspill for subscription ${selectedSubscription.id}`,
              packBreakdown: packRows
                .filter((pack) => pack.packSize && pack.packCount)
                .map((pack) => ({
                  packSize: Number(pack.packSize),
                  packCount: Number(pack.packCount),
                })),
            });
          }}
          className="space-y-3"
        >
          <div>
            <label className="block text-sm text-gray-700 mb-1">Customer</label>
            <select
              value={customerId}
              onChange={(e) => {
                setCustomerId(e.target.value);
                setSubscriptionId('');
              }}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
            >
              <option value="">Select customer</option>
              {customers?.data?.map((customer) => (
                <option key={customer.id} value={customer.id}>{customer.name}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm text-gray-700 mb-1">Base Subscription</label>
            <select
              value={subscriptionId}
              onChange={(e) => setSubscriptionId(e.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
              disabled={!customerId}
            >
              <option value="">Select subscription</option>
              {subscriptions.map((subscription) => (
                <option key={subscription.id} value={subscription.id}>
                  {subscription.productVariant.product.name} | {subscription.deliverySession} | base {subscription.quantity}
                </option>
              ))}
            </select>
          </div>

          {selectedSubscription && (
            <div className="rounded-md border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-900">
              <p className="font-medium">{selectedSubscription.productVariant.product.name}</p>
              <p>
                Base subscription: {selectedSubscription.quantity} | {selectedSubscription.deliverySession} | Route {selectedSubscription.route?.name ?? 'Unassigned'}
              </p>
              <p className="text-xs mt-1">
                Base packs: {selectedSubscription.packs?.length ? selectedSubscription.packs.map((pack) => `${pack.packCount} x ${Number(pack.packSize)}L`).join(', ') : 'No pack breakdown'}
              </p>
            </div>
          )}

          <div>
            <label className="block text-sm text-gray-700 mb-1">Extra Quantity</label>
            <input
              type="number"
              step="0.001"
              min="0.001"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
            />
          </div>

          <div className="rounded-md border border-gray-200 p-3">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-900">Overspill Pack Breakdown</p>
              <button
                type="button"
                onClick={() => setPackRows((prev) => [...prev, { packSize: '', packCount: '' }])}
                className="rounded-md border border-gray-300 px-2 py-1 text-xs"
              >
                + Add Pack
              </button>
            </div>
            <div className="space-y-2">
              {packRows.map((pack, index) => (
                <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-2">
                  <input
                    type="number"
                    step="0.001"
                    min="0.001"
                    value={pack.packSize}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packSize: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Pack size (L)"
                  />
                  <input
                    type="number"
                    step="1"
                    min="1"
                    value={pack.packCount}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packCount: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Count"
                  />
                  <button
                    type="button"
                    onClick={() => setPackRows((prev) => (prev.length === 1 ? [{ packSize: '', packCount: '' }] : prev.filter((_, rowIndex) => rowIndex !== index)))}
                    className="rounded-md border border-red-200 px-2 py-2 text-xs text-red-700"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
            {packMismatch && <p className="mt-2 text-xs text-red-700">Pack total must match extra quantity.</p>}
          </div>

          <div>
            <label className="block text-sm text-gray-700 mb-1">Notes</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={2}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              placeholder="Optional note for this overspill delivery"
            />
          </div>

          <p className="text-xs text-gray-500">Delivery date: {date}</p>
          {mutation.isError && <p className="text-sm text-red-600">Failed to add overspill. Please try again.</p>}
          <div className="flex justify-end gap-2">
            <button type="button" onClick={onClose} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">Cancel</button>
            <button
              type="submit"
              disabled={mutation.isPending || !selectedSubscription || packMismatch}
              className="rounded-md bg-amber-600 px-3 py-1.5 text-sm text-white hover:bg-amber-700 disabled:opacity-50"
            >
              {mutation.isPending ? 'Adding…' : 'Add Overspill'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function AddOrderModal({ date, onClose }: { date: string; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ customerId: '', productVariantId: '', quantity: '', deliverySession: 'morning' });
  const [packRows, setPackRows] = useState<Array<{ packSize: string; packCount: string }>>([{ packSize: '', packCount: '' }]);
  const { modalRef: addModalRef } = useModalFocusTrap(true, onClose);

  const { data: customers } = useQuery({
    queryKey: ['customers-select'],
    queryFn: () => api.get<{ data: Array<{ id: string; name: string }> }>('/api/v1/customers?limit=200&status=active'),
  });

  const { data: products } = useQuery({
    queryKey: ['products-select'],
    queryFn: () => api.get<{ data: Array<{ id: string; name: string; variants: Array<{ id: string; unitType: string; quantityPerUnit: number }> }> }>('/api/v1/products?limit=200'),
  });

  const mutation = useMutation({
    mutationFn: (data: { customerId: string; productVariantId: string; quantity: number; deliveryDate: string; deliverySession: string; packBreakdown: Array<{ packSize: number; packCount: number }> }) =>
      api.post('/api/v1/orders', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      onClose();
    },
  });

  const allVariants = products?.data?.flatMap((p) =>
    (p.variants ?? []).map((v) => ({ ...v, productName: p.name }))
  ) ?? [];
  const packTotal = packRows.reduce((sum, pack) => sum + (Number(pack.packSize) || 0) * (Number(pack.packCount) || 0), 0);
  const quantityValue = Number(form.quantity);
  const hasPackRows = packRows.some((pack) => pack.packSize || pack.packCount);
  const packMismatch = hasPackRows && !Number.isNaN(quantityValue) && Math.abs(packTotal - quantityValue) > 0.001;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" role="dialog" aria-modal="true" aria-labelledby="add-order-title">
      <div ref={addModalRef} className="bg-white rounded-lg p-6 max-w-md w-full mx-4 shadow-xl">
        <h2 id="add-order-title" className="text-lg font-semibold text-gray-900 mb-3">Add One-Time Order</h2>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            mutation.mutate({
              ...form,
              quantity: Number(form.quantity),
              deliveryDate: date,
              packBreakdown: packRows
                .filter((pack) => pack.packSize && pack.packCount)
                .map((pack) => ({
                  packSize: Number(pack.packSize),
                  packCount: Number(pack.packCount),
                })),
            });
          }}
          className="space-y-3"
        >
          <div>
            <label className="block text-sm text-gray-700 mb-1">Customer</label>
            <select
              value={form.customerId}
              onChange={(e) => setForm({ ...form, customerId: e.target.value })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
              aria-label="Select customer"
            >
              <option value="">Select customer…</option>
              {customers?.data?.map((c) => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm text-gray-700 mb-1">Product Variant</label>
            <select
              value={form.productVariantId}
              onChange={(e) => setForm({ ...form, productVariantId: e.target.value })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
              aria-label="Select product variant"
            >
              <option value="">Select product…</option>
              {allVariants.map((v) => (
                <option key={v.id} value={v.id}>{v.productName} ({v.quantityPerUnit} {v.unitType})</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm text-gray-700 mb-1">Quantity</label>
            <input
              type="number"
              step="0.001"
              min="0.001"
              value={form.quantity}
              onChange={(e) => setForm({ ...form, quantity: e.target.value })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
              aria-label="Order quantity"
            />
          </div>
          <div>
            <label className="block text-sm text-gray-700 mb-1">Delivery Session</label>
            <select
              value={form.deliverySession}
              onChange={(e) => setForm({ ...form, deliverySession: e.target.value })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
            >
              <option value="morning">Morning</option>
              <option value="evening">Evening</option>
            </select>
          </div>
          <div className="rounded-md border border-gray-200 p-3">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-900">Pack Breakdown</p>
              <button
                type="button"
                onClick={() => setPackRows((prev) => [...prev, { packSize: '', packCount: '' }])}
                className="rounded-md border border-gray-300 px-2 py-1 text-xs"
              >
                + Add Pack
              </button>
            </div>
            <div className="space-y-2">
              {packRows.map((pack, index) => (
                <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-2">
                  <input
                    type="number"
                    step="0.001"
                    min="0.001"
                    value={pack.packSize}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packSize: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Pack size (L)"
                  />
                  <input
                    type="number"
                    step="1"
                    min="1"
                    value={pack.packCount}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packCount: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Count"
                  />
                  <button
                    type="button"
                    onClick={() => setPackRows((prev) => (prev.length === 1 ? [{ packSize: '', packCount: '' }] : prev.filter((_, rowIndex) => rowIndex !== index)))}
                    className="rounded-md border border-red-200 px-2 py-2 text-xs text-red-700"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
            {packMismatch && <p className="mt-2 text-xs text-red-700">Pack total must match quantity.</p>}
          </div>
          <p className="text-xs text-gray-500">Delivery date: {date}</p>
          {mutation.isError && <p className="text-sm text-red-600">Failed to add order. Please try again.</p>}
          <div className="flex justify-end gap-2">
            <button type="button" onClick={onClose} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">Cancel</button>
            <button type="submit" disabled={mutation.isPending || packMismatch} className="rounded-md bg-blue-600 px-3 py-1.5 text-sm text-white hover:bg-blue-700 disabled:opacity-50">
              {mutation.isPending ? 'Adding…' : 'Add Order'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function EditOrderModal({ order, onClose }: { order: DeliveryOrder; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [quantity, setQuantity] = useState(String(order.quantity));
  const [deliverySession, setDeliverySession] = useState(order.deliverySession);
  const [packRows, setPackRows] = useState<Array<{ packSize: string; packCount: string }>>(
    order.packs?.length
      ? order.packs.map((pack) => ({ packSize: String(pack.packSize), packCount: String(pack.packCount) }))
      : [{ packSize: '', packCount: '' }],
  );
  const { modalRef: editModalRef } = useModalFocusTrap(true, onClose);

  const mutation = useMutation({
    mutationFn: (data: { quantity: number; deliverySession: string; packBreakdown: Array<{ packSize: number; packCount: number }> }) => api.put(`/api/v1/orders/${order.id}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders-summary'] });
      onClose();
    },
  });
  const packTotal = packRows.reduce((sum, pack) => sum + (Number(pack.packSize) || 0) * (Number(pack.packCount) || 0), 0);
  const quantityValue = Number(quantity);
  const hasPackRows = packRows.some((pack) => pack.packSize || pack.packCount);
  const packMismatch = hasPackRows && !Number.isNaN(quantityValue) && Math.abs(packTotal - quantityValue) > 0.001;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" role="dialog" aria-modal="true" aria-labelledby="edit-order-title">
      <div ref={editModalRef} className="bg-white rounded-lg p-6 max-w-sm w-full mx-4 shadow-xl">
        <h2 id="edit-order-title" className="text-lg font-semibold text-gray-900 mb-3">Edit Order</h2>
        <p className="text-sm text-gray-600 mb-2">{order.customer.name} — {order.productVariant?.product?.name}</p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            mutation.mutate({
              quantity: Number(quantity),
              deliverySession,
              packBreakdown: packRows
                .filter((pack) => pack.packSize && pack.packCount)
                .map((pack) => ({
                  packSize: Number(pack.packSize),
                  packCount: Number(pack.packCount),
                })),
            });
          }}
          className="space-y-3"
        >
          <div>
            <label className="block text-sm text-gray-700 mb-1">Quantity</label>
            <input
              type="number"
              step="0.001"
              min="0.001"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
              required
              aria-label="Edit quantity"
            />
          </div>
          <div>
            <label className="block text-sm text-gray-700 mb-1">Delivery Session</label>
            <select
              value={deliverySession}
              onChange={(e) => setDeliverySession(e.target.value as 'morning' | 'evening')}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
            >
              <option value="morning">Morning</option>
              <option value="evening">Evening</option>
            </select>
          </div>
          <div className="rounded-md border border-gray-200 p-3">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-900">Pack Breakdown</p>
              <button
                type="button"
                onClick={() => setPackRows((prev) => [...prev, { packSize: '', packCount: '' }])}
                className="rounded-md border border-gray-300 px-2 py-1 text-xs"
              >
                + Add Pack
              </button>
            </div>
            <div className="space-y-2">
              {packRows.map((pack, index) => (
                <div key={index} className="grid grid-cols-[1fr_1fr_auto] gap-2">
                  <input
                    type="number"
                    step="0.001"
                    min="0.001"
                    value={pack.packSize}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packSize: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Pack size (L)"
                  />
                  <input
                    type="number"
                    step="1"
                    min="1"
                    value={pack.packCount}
                    onChange={(e) => setPackRows((prev) => prev.map((row, rowIndex) => rowIndex === index ? { ...row, packCount: e.target.value } : row))}
                    className="rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Count"
                  />
                  <button
                    type="button"
                    onClick={() => setPackRows((prev) => (prev.length === 1 ? [{ packSize: '', packCount: '' }] : prev.filter((_, rowIndex) => rowIndex !== index)))}
                    className="rounded-md border border-red-200 px-2 py-2 text-xs text-red-700"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
            {packMismatch && <p className="mt-2 text-xs text-red-700">Pack total must match quantity.</p>}
          </div>
          {mutation.isError && <p className="text-sm text-red-600">Failed to update order.</p>}
          <div className="flex justify-end gap-2">
            <button type="button" onClick={onClose} className="rounded-md border border-gray-300 px-3 py-1.5 text-sm">Cancel</button>
            <button type="submit" disabled={mutation.isPending || packMismatch} className="rounded-md bg-blue-600 px-3 py-1.5 text-sm text-white hover:bg-blue-700 disabled:opacity-50">
              {mutation.isPending ? 'Saving…' : 'Save'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
